blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [

    url(r'^$', login_required(views.ListPosts.as_view(), login_url='/'), name='post_list'),
    url(r'^feed$', views.ListFeed.as_view(), name='feed'),
    url(r'^feed/(?P<page>[0-9]+)$', views.ListFeed.as_view(), name='feed'),

    url(r'^new_post$', views.NewPost.as_view(), name='new_post'),
    url(r'^post/(?P<pk>[0-9]+)$', views.DetailPost.as_view(), name='post'),
    url(r'^delete_post/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='delete_post'),

    url(r'^users$', views.ListUsers.as_view(), name='users'),
    url(r'^users/(?P<page>[0-9]*)$', views.ListUsers.as_view(), name='users'),

    url(r'^user/(?P<pk>[0-9]+)$', views.DetailUser.as_view(), name='user'),
    url(r'^subscribe$', views.CreateSubscribe.as_view(), name='subscribe'),
    url(r'^subscribes_list$', views.SubscribesList.as_view(), name='subscribes'),
    url(r'^delete_subscribe/(?P<pk>[0-9]+)$', views.DeleteSubscribe.as_view(), name='delete_subscribe'),
    url(r'^set_read', views.SetRead.as_view(), name='set_read'),
]

test_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog import urls

from . import views

urlpatterns = [
    url(r'^$', views.Main.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'^logout$', views.Logout.as_view(), name='logout'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^oauth$', views.OAuth.as_view(), name='vk_auth'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=128)
    text = models.CharField(max_length=1024)
    date = models.DateTimeField(auto_now_add=True)


class Feed(models.Model):

    post = models.ForeignKey(Post)
    is_read = models.BooleanField()
    subscriber = models.ForeignKey(settings.AUTH_USER_MODEL)

# не использую ManyToMany поскольку не хочу изменять дефолтную модель User
class Subscribers(models.Model):
    blog = models.ForeignKey(settings.AUTH_USER_MODEL)
    subscriber = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='subs')

    class Meta:
        unique_together = ('blog', 'subscriber')


# Сигналы
# Поскольку всеравно нужно делать оповещение по почте, заодно обновляю ленты подписчиков
#   вместо того, что бы генерировать ленты по запросу
@receiver(post_save, sender=Post)
def on_add_post(sender, **kwargs):

    if kwargs['created']:
        post = kwargs['instance']
        subs_list = Subscribers.objects.filter(blog=post.author)
        print('======================')
        print('Отправка писем: ')

        for subs in subs_list:
            if subs.subscriber.email:
                print('mail to {} email: {}'.format(subs.subscriber.username,
                                                    subs.subscriber.email))
            print(subs.subscriber)
            Feed(post=post, subscriber=subs.subscriber, is_read=False).save()

@receiver(pre_delete, sender=Subscribers)
def on_unsubscribe(sender, **kwargs):
    """Обновляем ленту при отписке"""
    instance = kwargs['instance']
    Feed.objects.filter(subscriber=instance.subscriber, post__author=instance.blog).delete()



@receiver(post_save, sender=Subscribers)
def on_subscribe(sender, **kwargs):
    """Обновляем ленту при подписке"""
    if kwargs['created']:
        instance = kwargs['instance']
        post_list = Post.objects.filter(author=instance.blog)
        print(post_list)
        for post_ in post_list:
            Feed(subscriber=instance.subscriber, post=post_, is_read=False).save()

blog/views.py
from django.views import generic
from django import forms
from blog import models
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User


class ErrorMixin:

    def error(self,  error):
        return render(self.request, 'blog/error.html', {'error': error})


def set_title(title):
    """
    Создает декоратор, заменющий obj.get_context_data
    на obj.get_context_data + context['title'] = title
    """
    def decorator(obj):
        tmp = obj.get_context_data

        def wrapper(self, **kwargs):
            context = tmp(self, **kwargs)
            context['title'] = title
            return context

        obj.get_context_data = wrapper
        return obj
    return decorator


@set_title('Мои посты')
class ListPosts(generic.ListView):
    model = models.Post
    context_object_name = 'list_posts'
    paginate_by = 10

    def get_queryset(self):
        return models.Post.objects.filter(author=self.request.user.id)


class PostForm(forms.Form):
    model = models.Post

    title = forms.CharField(label='',
                            widget=forms.TextInput(attrs={'id': 'ti'}))
    text = forms.CharField(label='',
                           widget=forms.Textarea(attrs={'id': 'ta'}))


class DeletePost(generic.DeleteView, ErrorMixin):
    model = models.Post

    def delete(self, request, *args, **kwargs):
        """class DeletionMixin(object).delete() добавил проверку post.author == request.user"""
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        obj = self.get_object()
        if obj.author == request.user:
            obj.delete()
            return redirect(request.POST.get('redirect_url', default='/'))
        else:
            return self.error('Вы не можете удалять чужие записи')


@set_title('Новый пост')
class NewPost(generic.FormView):
    model = models.Post
    template_name = 'blog/post_form.html'
    form_class = PostForm

    def form_valid(self, form):
        title = form.cleaned_data['title']
        text = form.cleaned_data['text']
        author = self.request.user
        redirect_url = self.request.POST.get('redirect_url', default='/')
        models.Post(text=text, title=title, author=author).save()
        return redirect(redirect_url)

    def form_invalid(self, form):
        return render(self.request, 'error.html', {'error': 'ошибки в заполнении формы'})


@set_title('Пост')
class DetailPost(generic.DetailView):
    model = models.Post

    def get_context_data(self, **kwargs):
        context = super(generic.DetailView, self).get_context_data( **kwargs)

        if models.Feed.objects.filter(subscriber=self.request.user, post=kwargs['object']).exists():
            context['subscribed'] = True
            context['is_read'] = models.Feed.objects.get(subscriber=self.request.user, post=kwargs['object']).is_read
        return context


class DetailUser(generic.DetailView):
    model = User
    template_name = "blog/user_detail.html"

    def get_context_data(self, **kwargs):
        context = super(generic.DetailView, self).get_context_data(**kwargs)
        user = context['object']
        context['title'] = user.username
        context['list_posts'] = models.Post.objects.filter(author=user)
        if models.Subscribers.objects.filter(blog=user, subscriber=self.request.user).exists():
            context['subscribe'] = models.Subscribers.objects.get(blog=user, subscriber=self.request.user)

        return context


@set_title('Список пользователей')
class ListUsers(generic.ListView):
    template_name = 'blog/user_list.html'
    paginate_by = 7

    def get_queryset(self):
        return User.objects.exclude(id=self.request.user.id)


class DeleteSubscribe(generic.DeleteView):
    model = models.Subscribers

    def get_success_url(self):
        return self.request.POST.get('redirect_url', default='/blog')


class CreateSubscribe(generic.View, ErrorMixin):    # лениво использовать form ради одного поля
                                                    # при том что второе всеравно заполнять из request
    def post(self, request):
        subscriber = request.user
        try:
            blog_id = int(request.POST['blog'])
        except (ValueError, KeyError):
            return self.error('Неверный id блога')

        blog = get_object_or_404(User, pk=blog_id)
        if models.Subscribers.objects.filter(blog=blog, subscriber=subscriber).exists():
            return self.error('Вы уже подписаны')
        models.Subscribers(blog=blog, subscriber=subscriber).save()
        return redirect(request.POST.get('redirect_url', default='/'))


@set_title('Мои подписки')
class SubscribesList(generic.ListView):

    def get_queryset(self):
        return models.Subscribers.objects.filter(subscriber=self.request.user)


@set_title('Лента')
class ListFeed(generic.ListView):
    paginate_by = 3

    def get_queryset(self):
        return models.Feed.objects.filter(subscriber=self.request.user)


class SetRead(generic.View, ErrorMixin):

    def post(self, request):
        try:
            post_id = int(request.POST['post_id'])
        except (ValueError, KeyError):
            return self.error('Неверный id поста')
        obj = get_object_or_404(models.Feed, subscriber=request.user, post__id=post_id)
        obj.is_read = not obj.is_read
        obj.save()
        return redirect(request.POST.get('redirect_url', default='/'))

blog/templates/blog/error.html
{% extends 'blog/base.html' %}
{%  block content %}

{{error}}

{% endblock %}

blog/templates/blog/feed_list.html
{% extends 'blog/base.html' %}
{%  block content %}

    {% if not object_list %}
        Лента пуста
    {% else %}
        <table>
        {% for feed in object_list %}
        <tr>
            <td><a href="{% url 'blog:user' feed.post.author_id %}"> {{feed.post.author}} </a></td>
            <td><a href="{% url 'blog:post' feed.post.id %}">  {{feed.post.title}} </a></td>
            <td>    {{feed.post.date| date:"d.m.Y H:i:s"}}</td>
            <td>
                <form class="r_fromd" action="{% url 'blog:set_read' %}" method="post" >{% csrf_token %}
                     <input type="hidden"  name="redirect_url" value="{{request.path}}"/>
                     <input type="hidden" name="post_id" value = {{feed.post.id}} >
                    {% if  feed.is_read %}
                    <input type="submit" value = "Прочитан"/>
                    {% else %}
                    <input type="submit" value = "Не прочитан"/>
                    {% endif %}
                </form>
            </td>
        </tr>
        {% endfor %}
        </table>
    {% endif %}

 <hr>

{% if paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
        <a href="{% url 'blog:feed' page_obj.previous_page_number %}"><=</a>
    {% endif %}

    {{page_obj.number}} of {{paginator.num_pages}}

    {% if page_obj.has_next %}
        <a href="{% url 'blog:feed' page_obj.next_page_number %}">=></a>
    {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/menu_inline.html
<a class="menu_item" href="{% url 'blog:feed'  %}"> Лента </a>
<a class="menu_item" href="{% url 'blog:post_list' %}"> Мои посты </a>
<a class="menu_item" href="{% url 'blog:subscribes' %}"> Подписки </a>
<a class="menu_item" href="{% url 'blog:users' %}"> Пользователи </a>
<a class="menu_item" href="{% url 'home' %}"> Назад </a>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{%  block content %}

    {{object.title}}: - Удалить?
    <br><br><br>
    <form method ="post" action="{% url 'blog:delete_post' object.id %}">{% csrf_token %}
        <input type="submit" value="Удалить">
        <input type="hidden" name="redirect_url" value="{% url 'blog:post_list' %}"/>
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{%  block content %}

        <a href="{% url 'blog:user' object.author.id %}">{{object.author}}</a> : {{object.title}}


         {% if subscribed %}

          <form class="r_form" action="{% url 'blog:set_read' %}" method="post" >{% csrf_token %}
            <input type="hidden"  name="redirect_url" value="{{request.path}}"/>
            <input type="hidden" name="post_id" value = {{object.id}} >
            {% if is_read %}
            <input type="submit" value = "Прочитан"/>
            {% else %}
            <input type="submit" value = "Не прочитан"/>
            {% endif %}
        </form>

        {% endif %}
    <p>
        {{object.text}}
    </p>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{%  block content %}

    <form method="post" action="{% url 'blog:new_post' %}">{% csrf_token  %}
        {{form.as_p}}
        <input type="hidden" name="redirect_url" value = "{% url 'blog:post_list' %}" />
    <input type="submit" value="Сохранить">
    </form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{%  block content %}

<a href="{% url  'blog:new_post' %}">Новый пост</a>
<hr>
{% if list_posts %}
<table >

    {% for post in list_posts %}
    <tr>
        <td><a href ="{% url 'blog:post' post.id %}">{{post.title}}</a> </td>
        <td> {{post.date| date:"d.m.Y H:i:s"}} </td>
        <td><a href="{% url 'blog:delete_post' post.id %}"> удалить </a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
У вас пока нет постов
{% endif %}

{% endblock %}

blog/templates/blog/subscribers_list.html
{% extends 'blog/base.html' %}
{%  block content %}


{% if object_list %}

    {% for x in object_list %}

        <a href="{% url 'blog:user' x.blog.id %}" > {{x.blog.username}} </a>

        <form action="{% url 'blog:delete_subscribe' x.id %}" method="post" class="r_form">{% csrf_token %}
            <input type="hidden" name="redirect_url" value="{{request.path}}"/>
            <input type="submit" value="отписаться"/>
        </form>

       <br><br>
    {% endfor %}

{% else %}
Список пуст
{% endif %}

{% endblock %}

blog/templates/blog/user_detail.html
{% extends 'blog/base.html' %}
{%  block content %}

     {{object}}

    {% if subscribe %}
        <form action="{% url 'blog:delete_subscribe' subscribe.id %}" method="post" class="r_form">{% csrf_token %}
            <input type="hidden" name="redirect_url" value="{{request.path}}"/>
            <input type="submit" value="отписаться"/>
        </form>
    {% else %}
        <form action="{% url 'blog:subscribe' %}" method="post" class="r_form" >{% csrf_token %}
            <input type="hidden" name="blog" value="{{user.id}}"/>
            <input type="hidden" name="redirect_url" value="{{request.path}}"/>
            <input type="submit" value="Подписаться"/>
        </form>
    {% endif %}

<hr>
{% if list_posts %}
    Посты:
    <table >
        {% for post in list_posts %}
        <tr>
            <td>
            <a href ="{% url 'blog:post' post.id %}">{{post.title}}</a>
            </td>
            <td> {{post.date| date:"d.m.Y H:i:s"}} </td>
         </tr>
        {% endfor %}
    </table>
{% else %}
    У пользователя нет постов
{% endif %}

{% endblock %}

blog/templates/blog/user_list.html
{% extends 'blog/base.html' %}
{%  block content %}

{% for user in object_list %}
    <a href = "{% url 'blog:user' user.id %}"> {{user.username}}</a>
    <br><br>
{% endfor %}

 <hr>

{% if paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
        <a href="{% url 'blog:users' page_obj.previous_page_number %}"><=</a>
    {% endif %}

    {{page_obj.number}} of {{paginator.num_pages}}

    {% if page_obj.has_next %}
        <a href="{% url 'blog:users' page_obj.next_page_number %}">=></a>
    {% endif %}
{% endif %}

{% endblock %}